name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build-script: build:linux
          - os: windows-latest
            build-script: build:win
          - os: macos-latest
            build-script: build:mac

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Cache Electron + electron-builder (Linux/macOS)
      - name: Cache Electron (Unix)
        if: runner.os != 'Windows'
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-electron-

      # Cache Electron + electron-builder (Windows)
      - name: Cache Electron (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v5
        with:
          path: |
            ~\AppData\Local\electron\Cache
            ~\AppData\Local\electron-builder\Cache
          key: ${{ runner.os }}-electron-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-electron-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Rebuild native deps
        run: bunx electron-builder install-app-deps

      - name: Build & Package
        run: bun run ${{ matrix.build-script }}

      - name: Get version
        shell: bash
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Release the artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.exe,dist/*.dmg,dist/*.AppImage,dist/*.deb,dist/*.snap"
          allowUpdates: true
          tag: "v${{ env.PACKAGE_VERSION }}"
          commit: "${{ github.sha }}"